# Generated by Django 3.1.5 on 2021-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_waifu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='waifu',
            name='age',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
