# Generated by Django 3.1.5 on 2021-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210105_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waifu',
            old_name='blood',
            new_name='bloodType',
        ),
        migrations.AddField(
            model_name='waifu',
            name='bust',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='waifu',
            name='trashCount',
            field=models.IntegerField(default=None),
        ),
    ]
