# Generated by Django 3.1.5 on 2021-01-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
